[vars]
BASE_URL = "https://site.com/api/v1"
LISTING_ID = "ABC13245"

[[requests]]
name = "Login"
url = "{BASE_URL}/auth/login"
method = "POST"
query = { limit = 10, offset = 0 }
headers = { Content-Type = "application/json", Accept = "application/json", Authorization = "Bearer {TOKEN}" }
body = { email = "admin@site.com", password = "qweqweqwe" }

[[requests]]
name = "Get Listing"
url = "{BASE_URL}/auth/listings/{LISTING_ID}"
method = "GET"
headers = { Content-Type = "application/json", Authorization = "Bearer {TOKEN}" }
