[vars]
BASE_URL = "https://connect.uplisting.io"
LISTING_ID = ""

[[requests]]
name = "Get Properties"
url = "{BASE_URL}/properties"
method = "GET"
# query = { limit = 10, offset = 0 }
headers = { Content-Type = "application/json", Authorization = "Basic {API_KEY}" }
# body = { email = "admin@site.com", password = "qweqweqwe" }

[[requests]]
name = "Get Bookings"
url = "{BASE_URL}/bookings/{LISTING_ID}"
method = "GET"
query = { from = "2020-12-10", to = "2020-12-20" }
headers = { Content-Type = "application/json", Authorization = "Basic {API_KEY}" }
